# workflow name
name: kk-api

# master branch on push, auto run
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: 1. 检查master分支
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: 2. 设置Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3. 缓存
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}

      - name: 4. 安装插件
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export TZ='Asia/Shanghai'
          yarn install
      - name: 5. 开始构建
        run: |
          yarn run build
      - name: 6. 推送产物
        #  git push --force --all https://${{ secrets.GITEE_TOKEN }}@${{ secrets.GITEE_REPO }}
        run: |
          cp ./vercel.json dist
          cp ./package.json dist
          cp ./yarn.lock dist
          cd ./dist
          ls
          git init
          git config --global user.name '${{ secrets.GIT_USER }}'
          git config --global user.email '${{ secrets.GIT_MAIL }}'
          git add .
          git commit -m "Update"
          git push --force --all https://${{ secrets.BIT_TOKEN }}@${{ secrets.BIT_REPO }}
          cd ..
